spring.application.name=smart-drain

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smart_drain}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

server.port=8080
